In [1]:
import pandas as pd
candy = pd.read_csv("candyhierarchy2017.csv", encoding='ISO-8859-1')
candy.head(2)

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"

In [2]:
metro = pd.read_csv("MetObjects.csv")
metro.head(2)

C:\Users\atanu\AppData\Local\Temp\ipykernel_20600\3973488846.py:1: DtypeWarning: Columns (5,11,35,36,37,39,46) have mixed types. Specify dtype option on import or set low_memory=False.
  metro = pd.read_csv("MetObjects.csv")

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,River,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979.0,Coin,One-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/1,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980.0,Coin,Ten-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/2,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN

# Chapter 7 : Fill in missing data

In [29]:
candy.dtypes

Internal ID                                                                                 int64
Q1: GOING OUT?                                                                             object
Q2: GENDER                                                                                 object
Q3: AGE                                                                                    object
Q4: COUNTRY                                                                                object
Q5: STATE, PROVINCE, COUNTY, ETC                                                           object
Q6 | 100 Grand Bar                                                                         object
Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)     object
Q6 | Any full-sized candy bar                                                              object
Q6 | Black Jacks                                                                           object
Q6 | Bonkers (the candy)                                                                   object
Q6 | Bonkers (the board game)                                                              object
Q6 | Bottle Caps                                                                           object
Q6 | Box'o'Raisins                                                                         object
Q6 | Broken glow stick                                                                     object
Q6 | Butterfinger                                                                          object
Q6 | Cadbury Creme Eggs                                                                    object
Q6 | Candy Corn                                                                            object
Q6 | Candy that is clearly just the stuff given out for free at restaurants                object
Q6 | Caramellos                                                                            object
Q6 | Cash, or other forms of legal tender                                                  object
Q6 | Chardonnay                                                                            object
Q6 | Chick-o-Sticks (we donÕt know what that is)                                           object
Q6 | Chiclets                                                                              object
Q6 | Coffee Crisp                                                                          object
Q6 | Creepy Religious comics/Chick Tracts                                                  object
Q6 | Dental paraphenalia                                                                   object
Q6 | Dots                                                                                  object
Q6 | Dove Bars                                                                             object
Q6 | Fuzzy Peaches                                                                         object
Q6 | Generic Brand Acetaminophen                                                           object
Q6 | Glow sticks                                                                           object
Q6 | Goo Goo Clusters                                                                      object
Q6 | Good N' Plenty                                                                        object
Q6 | Gum from baseball cards                                                               object
Q6 | Gummy Bears straight up                                                               object
Q6 | Hard Candy                                                                            object
Q6 | Healthy Fruit                                                                         object
Q6 | Heath Bar                                                                             object
Q6 | Hershey's Dark Chocolate                                                              object
Q6 | HersheyÕs Milk Chocolate                                                              object
Q6 | Hershey's Kisses                                                                      object
Q6 | Hugs (actual physical hugs)                                                           object
Q6 | Jolly Rancher (bad flavor)                                                            object
Q6 | Jolly Ranchers (good flavor)                                                          object
Q6 | JoyJoy (Mit Iodine!)                                                                  object
Q6 | Junior Mints                                                                          object
Q6 | Senior Mints                                                                          object
Q6 | Kale smoothie                                                                         object
Q6 | Kinder Happy Hippo                                                                    object
Q6 | Kit Kat                                                                               object
Q6 | LaffyTaffy                                                                            object
Q6 | LemonHeads                                                                            object
Q6 | Licorice (not black)                                                                  object
Q6 | Licorice (yes black)                                                                  object
Q6 | Lindt Truffle                                                                         object
Q6 | Lollipops                                                                             object
Q6 | Mars                                                                                  object
Q6 | Maynards                                                                              object
Q6 | Mike and Ike                                                                          object
Q6 | Milk Duds                                                                             object
Q6 | Milky Way                                                                             object
Q6 | Regular M&Ms                                                                          object
Q6 | Peanut M&MÕs                                                                          object
Q6 | Blue M&M's                                                                            object
Q6 | Red M&M's                                                                             object
Q6 | Green Party M&M's                                                                     object
Q6 | Independent M&M's                                                                     object
Q6 | Abstained from M&M'ing.                                                               object
Q6 | Minibags of chips                                                                     object
Q6 | Mint Kisses                                                                           object
Q6 | Mint Juleps                                                                           object
Q6 | Mr. Goodbar                                                                           object
Q6 | Necco Wafers                                                                          object
Q6 | Nerds                                                                                 object
Q6 | Nestle Crunch                                                                         object
Q6 | Now'n'Laters                                                                          object
Q6 | Peeps                                                                                 object
Q6 | Pencils                                                                               object
Q6 | Pixy Stix                                                                             object
Q6 | Real Housewives of Orange County Season 9 Blue-Ray                                    object
Q6 | ReeseÕs Peanut Butter Cups                                                            object
Q6 | Reese's Pieces                                                                        object
Q6 | Reggie Jackson Bar                                                                    object
Q6 | Rolos                                                                                 object
Q6 | Sandwich-sized bags filled with BooBerry Crunch                                       object
Q6 | Skittles                                                                              object
Q6 | Smarties (American)                                                                   object
Q6 | Smarties (Commonwealth)                                                               object
Q6 | Snickers                                                                              object
Q6 | Sourpatch Kids (i.e. abominations of nature)                                          object
Q6 | Spotted Dick                                                                          object
Q6 | Starburst                                                                             object
Q6 | Sweet Tarts                                                                           object
Q6 | Swedish Fish                                                                          object
Q6 | Sweetums (a friend to diabetes)                                                       object
Q6 | Take 5                                                                                object
Q6 | Tic Tacs                                                                              object
Q6 | Those odd marshmallow circus peanut things                                            object
Q6 | Three Musketeers                                                                      object
Q6 | Tolberone something or other                                                          object
Q6 | Trail Mix                                                                             object
Q6 | Twix                                                                                  object
Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein                object
Q6 | Vicodin                                                                               object
Q6 | Whatchamacallit Bars                                                                  object
Q6 | White Bread                                                                           object
Q6 | Whole Wheat anything                                                                  object
Q6 | York Peppermint Patties                                                               object
Q7: JOY OTHER                                                                              object
Q8: DESPAIR OTHER                                                                          object
Q9: OTHER COMMENTS                                                                         object
Q10: DRESS                                                                                 object
Unnamed: 113                                                                               object
Q11: DAY                                                                                   object
Q12: MEDIA [Daily Dish]                                                                   float64
Q12: MEDIA [Science]                                                                      float64
Q12: MEDIA [ESPN]                                                                         float64
Q12: MEDIA [Yahoo]                                                                        float64
Click Coordinates (x, y)                                                                   object
dtype: object

In [30]:
pd.set_option('display.max_rows', None)
candy['Q12: MEDIA [Daily Dish]'].isnull().sum()/len(candy)

0.9654471544715447

In [31]:
candy['Q12: MEDIA [Daily Dish]'].fillna(candy['Q12: MEDIA [Daily Dish]'].mean(),inplace=True)

In [32]:
candy['Q12: MEDIA [Daily Dish]'].isnull().sum()/len(candy)

0.0

# Chapter 7 : Replace values

In [34]:
candy['Q2: GENDER'].value_counts()

Male                  1467
Female                 839
I'd rather not say      83
Other                   30
Name: Q2: GENDER, dtype: int64

In [38]:
candy['Q2: GENDER'].replace(["Male", "Female","I'd rather not say","Other"], ['M', 'F','X','O'], inplace=True)

In [39]:
candy['Q2: GENDER'].value_counts()

M    1467
F     839
X      83
O      30
Name: Q2: GENDER, dtype: int64

# Chapter 8 : Create hierarchical index

In [6]:
metro_index = metro.set_index(['Department', 'Object Name'])

In [7]:
metro_index.sort_index()

                                                         Object Number  \
Department        Object Name
Arms and Armor    2 Swords (Dha) with scabbard  1979.448.1a, b, .2a, b
                  Adze                                      36.25.1847
                  Ahlspiess                                  14.25.396
                  Air gun                                    32.75.105
                  Album                                     36.120.699
...                                                                ...
The American Wing Étagère                                        69.89
                  Étagère                                     1978.289
                  Étagère                                     1971.219
                  Étagère                                     1991.230
                  Étagère shelves                             1971.220

                                                Is Highlight  \
Department        Object Name
Arms and Armor    2 Swords (Dha) with scabbard         False
                  Adze                                 False
                  Ahlspiess                            False
                  Air gun                              False
                  Album                                False
...                                                      ...
The American Wing Étagère                              False
                  Étagère                              False
                  Étagère                               True
                  Étagère                              False
                  Étagère shelves                      False

                                                Is Timeline Work  \
Department        Object Name
Arms and Armor    2 Swords (Dha) with scabbard             False
                  Adze                                     False
                  Ahlspiess                                False
                  Air gun                                  False
                  Album                                    False
...                                                          ...
The American Wing Étagère                                  False
                  Étagère                                  False
                  Étagère                                  False
                  Étagère                                  False
                  Étagère shelves                          False

                                                Is Public Domain  Object ID  \
Department        Object Name
Arms and Armor    2 Swords (Dha) with scabbard             False      24878
                  Adze                                     False      30824
                  Ahlspiess                                 True      26797
                  Air gun                                  False      32292
                  Album                                     True      24642
...                                                          ...        ...
The American Wing Étagère                                   True       3553
                  Étagère                                  False       3554
                  Étagère                                   True       3555
                  Étagère                                   True      14297
                  Étagère shelves                           True       3557

                                               Gallery Number  AccessionYear  \
Department        Object Name
Arms and Armor    2 Swords (Dha) with scabbard            NaN         1979.0
                  Adze                                    NaN         1936.0
                  Ahlspiess                               NaN         1914.0
                  Air gun                                 NaN         1932.0
                  Album                                   NaN         1936.0
...                                                       ...            ...
The American Wing Étagère                                 774         1969.0
                  Étagère                                 774         1978.0
                  Étagère                                 714         1971.0
                  Étagère                                 774         1991.0
                  Étagère shelves                         714         1971.0

                                                                                           Title  \
Department        Object Name
Arms and Armor    2 Swords (Dha) with scabbard                      2 Swords (Dha) with scabbard
                  Adze                                                                      Adze
                  Ahlspiess                                                            Ahlspiess
                  Air gun                                                                Air Gun
                  Album                         Album of Designs for Metal Carving (Chōsen Gafu)
...                                                                                          ...
The American Wing Étagère                                                                Étagère
                  Étagère                                                                Étagère
                  Étagère                                                                Étagère
                  Étagère                                                                Étagère
                  Étagère shelves                                                Étagère Shelves

                                                          Culture Period  ...  \
Department        Object Name                                             ...
Arms and Armor    2 Swords (Dha) with scabbard            Burmese    NaN  ...
                  Adze                           Philippine, Sulu    NaN  ...
                  Ahlspiess                     probably Austrian    NaN  ...
                  Air gun                                Austrian    NaN  ...
                  Album                                  Japanese    NaN  ...
...                                                           ...    ...  ...
The American Wing Étagère                                American    NaN  ...
                  Étagère                                American    NaN  ...
                  Étagère                                American    NaN  ...
                  Étagère                                American    NaN  ...
                  Étagère shelves                        American    NaN  ...

                                                River       Classification  \
Department        Object Name
Arms and Armor    2 Swords (Dha) with scabbard    NaN               Swords
                  Adze                            NaN      Shafted Weapons
                  Ahlspiess                       NaN      Shafted Weapons
                  Air gun                         NaN    Firearms-Guns-Air
                  Album                           NaN  Books & Manuscripts
...                                               ...                  ...
The American Wing Étagère                         NaN                  NaN
                  Étagère                         NaN                  NaN
                  Étagère                         NaN                  NaN
                  Étagère                         NaN                  NaN
                  Étagère shelves                 NaN                  NaN

                                                Rights and Reproduction  \
Department        Object Name
Arms and Armor    2 Swords (Dha) with scabbard                      NaN
                  Adze                                              NaN
                  Ahlspiess                                         NaN
                  Air gun                                           NaN
                  Album                                             NaN
...                                                                 ...
The American Wing Étagère                                           NaN
                  Étagère                                           NaN
                  Étagère                                           NaN
                  Étagère                                           NaN
                  Étagère shelves                                   NaN

                                                                                    Link Resource  \
Department        Object Name
Arms and Armor    2 Swords (Dha) with scabbard  http://www.metmuseum.org/art/collection/search...
                  Adze                          http://www.metmuseum.org/art/collection/search...
                  Ahlspiess                     http://www.metmuseum.org/art/collection/search...
                  Air gun                       http://www.metmuseum.org/art/collection/search...
                  Album                         http://www.metmuseum.org/art/collection/search...
...                                                                                           ...
The American Wing Étagère                       http://www.metmuseum.org/art/collection/search...
                  Étagère                       http://www.metmuseum.org/art/collection/search...
                  Étagère                       http://www.metmuseum.org/art/collection/search...
                  Étagère                       http://www.metmuseum.org/art/collection/search...
                  Étagère shelves               http://www.metmuseum.org/art/collection/search...

                                                                    Object Wikidata URL  \
Department        Object Name
Arms and Armor    2 Swords (Dha) with scabbard                                      NaN
                  Adze                                                              NaN
                  Ahlspiess                                                         NaN
                  Air gun                                                           NaN
                  Album                                                             NaN
...                                                                                 ...
The American Wing Étagère                                                           NaN
                  Étagère                                                           NaN
                  Étagère                       https://www.wikidata.org/wiki/Q29382922
                  Étagère                                                           NaN
                  Étagère shelves                                                   NaN

                                               Metadata Date  \
Department        Object Name
Arms and Armor    2 Swords (Dha) with scabbard           NaN
                  Adze                                   NaN
                  Ahlspiess                              NaN
                  Air gun                                NaN
                  Album                                  NaN
...                                                      ...
The American Wing Étagère                                NaN
                  Étagère                                NaN
                  Étagère                                NaN
                  Étagère                                NaN
                  Étagère shelves                        NaN

                                                                              Repository  \
Department        Object Name
Arms and Armor    2 Swords (Dha) with scabbard  Metropolitan Museum of Art, New York, NY
                  Adze                          Metropolitan Museum of Art, New York, NY
                  Ahlspiess                     Metropolitan Museum of Art, New York, NY
                  Air gun                       Metropolitan Museum of Art, New York, NY
                  Album                         Metropolitan Museum of Art, New York, NY
...                                                                                  ...
The American Wing Étagère                       Metropolitan Museum of Art, New York, NY
                  Étagère                       Metropolitan Museum of Art, New York, NY
                  Étagère                       Metropolitan Museum of Art, New York, NY
                  Étagère                       Metropolitan Museum of Art, New York, NY
                  Étagère shelves               Metropolitan Museum of Art, New York, NY

                                                    Tags  \
Department        Object Name
Arms and Armor    2 Swords (Dha) with scabbard       NaN
                  Adze                               NaN
                  Ahlspiess                          NaN
                  Air gun                            NaN
                  Album                         Ornament
...                                                  ...
The American Wing Étagère                            NaN
                  Étagère                            NaN
                  Étagère                            NaN
                  Étagère                            NaN
                  Étagère shelves                    NaN

                                                                             Tags AAT URL  \
Department        Object Name
Arms and Armor    2 Swords (Dha) with scabbard                                        NaN
                  Adze                                                                NaN
                  Ahlspiess                                                           NaN
                  Air gun                                                             NaN
                  Album                         http://vocab.getty.edu/page/aat/300164595
...                                                                                   ...
The American Wing Étagère                                                             NaN
                  Étagère                                                             NaN
                  Étagère                                                             NaN
                  Étagère                                                             NaN
                  Étagère shelves                                                     NaN

                                                                    Tags Wikidata URL
Department        Object Name
Arms and Armor    2 Swords (Dha) with scabbard                                    NaN
                  Adze                                                            NaN
                  Ahlspiess                                                       NaN
                  Air gun                                                         NaN
                  Album                         https://www.wikidata.org/wiki/Q335261
...                                                                               ...
The American Wing Étagère                                                         NaN
                  Étagère                                                         NaN
                  Étagère                                                         NaN
                  Étagère                                                         NaN
                  Étagère shelves                                                 NaN

[34414 rows x 52 columns]

# Chapter 8 : Pivot the data

In [12]:
metro.pivot_table(index='Department', columns='Culture', values='Object ID', aggfunc='sum')

Culture,"""Peking"" work","Abor, Burmese",Acheen,Afghan,"Afghan or Persian, Pathan Tribes, Afridi","Afghan, Khyber","Afghan; barrel, Indian","Afghan; lock, British",Afghanistan,Afghanistan (Hadda),...,probably Tibetan,probably Tibetan or Chinese,probably Tibetan or Mongolian,probably Turkish,probably Vietnamese,probably West Slavic,"saddle plate, Chinese or Tibetan; harness fittings, Tibetan",southern German or Tyrolese; cranequin probably German or Swiss,"spearhead, Chinese or Mongolian; case, Tibetan","staff, Indian; banner, Mahdist Sudanese"
Department,,,,,,,,,,,,,,,,,,,,,
Arms and Armor,32401.0,32071.0,155599.0,246589.0,31782.0,31613.0,30615.0,91812.0,NaN,NaN,...,368827.0,214845.0,35629.0,49711.0,29987.0,29277.0,24977.0,25600.0,26615.0,26978.0
Asian Art,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,462753.0,77002.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
European Sculpture and Decorative Arts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Medieval Art,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Modern and Contemporary Art,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
The American Wing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Chapter 10 : Grouping with Dicts/Series

In [19]:
candy_=candy.dropna(subset=['Q2: GENDER', 'Q3: AGE'])

In [21]:
candy_ = candy_[candy_['Q3: AGE'].apply(lambda x: x.isnumeric())]

In [22]:
candy_[['Q3: AGE']] = candy_[['Q3: AGE']].astype(int)

In [24]:
candy_agg = candy_.groupby('Q2: GENDER').agg({'Q3: AGE' : 'mean'})
candy_agg.head()

                      Q3: AGE
Q2: GENDER
Female              40.671551
I'd rather not say  58.852941
Male                42.954450
Other               41.068966

# Chapter 10 : Grouping with Functions

In [27]:
def max_age(x):
    return x.max()

candy_max_age_by_gender = candy_.groupby('Q2: GENDER').agg({'Q3: AGE' : max_age})
candy_max_age_by_gender.head()

                    Q3: AGE
Q2: GENDER
Female                   73
I'd rather not say     1000
Male                     90
Other                   312

# Chapter 11 : Convert between string and date time

In [12]:
import pandas as pd
bb = pd.read_excel("BOING-BOING-CANDY-HIERARCHY-2016-SURVEY-Responses.xlsx")
bb.head(2)

,Timestamp,Are you going actually going trick or treating yourself?,Your gender:,How old are you?,Which country do you live in?,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
0,2016-10-24 05:09:23.033,No,Male,22,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN
1,2016-10-24 05:09:54.798,No,Male,45,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN

In [31]:
from datetime import datetime
def date_convert(date_to_convert):
     return datetime.strftime(date_to_convert,'%m/%d/%Y')
bb['ts_string'] = bb['Timestamp'].apply(date_convert)
bb.loc[:,['Timestamp','ts_string']].head()

                Timestamp   ts_string
0 2016-10-24 05:09:23.033  10/24/2016
1 2016-10-24 05:09:54.798  10/24/2016
2 2016-10-24 05:13:06.734  10/24/2016
3 2016-10-24 05:14:17.192  10/24/2016
4 2016-10-24 05:14:24.625  10/24/2016

In [32]:
bb.loc[:,['Timestamp','ts_string']].dtypes

Timestamp    datetime64[ns]
ts_string            object
dtype: object

# Chapter 11 : Generate date range

In [33]:
df = pd.DataFrame(pd.date_range(start='2022-01-01', end='2022-01-31'), columns=['date'])
df.head(3)

        date
0 2022-01-01
1 2022-01-02
2 2022-01-03